### ISSUE TITLE
CHECK_UPDATES CRITICAL on non-critical updates

### ISSUE THREAD

**Issue by olebowle** [matteocorti/check_updates#18]
Hi,

thanks for the plugin! I noticed that it returns a critical state, even though there are no critical updates available. We are on CentOS7.

```console
# /usr/lib64/nagios/plugins/check_updates
CHECK_UPDATES CRITICAL - 6 non-critical updates available | total_updates=6;0;0 security_updates=0;0;0
htop.x86_64
kernel.x86_64
kernel-headers.x86_64
kernel-tools.x86_64
kernel-tools-libs.x86_64
python-perf.x86_64

# echo $?
2
```

**Comment by matteocorti** [comment]
Hi

Mmm it is terminology problem. "non-critical" refers to the fact that the updates are not security related. The result of the plugin is "CRITICAL" as the number of available updates is greater than the ```--critical``` option (defaults to 1). You can specify ```--security-only``` if you don't want to consider bug fixes.

I will change the output as it is very confusing!

Thanks for the hint.

Matteo

**Comment by olebowle** [comment]
Ah, I see.

I think it would be nice if the plugin would return WARNING if non-critical updates are available and CRITICAL in the case of security-related ones. Does that make sense? This mode could be enabled using an option for backward compatibility.

**Comment by olebowle** [comment]
That's alright. I added `--critical=100` and I think this will work just fine for me.
