### ISSUE TITLE
check_updates on CentOS 8 ?

### ISSUE THREAD

**Issue by michaelschefczyk** [matteocorti/check_updates#26]
Dear Mr. Corti,

Will this great plugin be available on CentOS 8 sometime? I find it a great feature in Nagios to be reminded via your plugin that the system needs to be rebooted because yum-cron (or dnf-automatic, now) did install a newer kernel, for example. In CentOS 8, the package is missing, unfortunately. If one does copy the perl script manually, the script cannot run. Even after modifying the first line to #!/usr/bin/perl, CentOS 8 does complain "Can't locate Readonly.pm in @INC" and that does not seem to be trivial to solve.

Regards,

Michael Schefczyk

**Comment by matteocorti** [comment]
Dear Micheal

CentOS will include the same packages as RedHat. I have no way to decide what RedHat will put in its own distribution.

I provide a `.spec` file so that an RPM can be easy built

Matteo
