### ISSUE TITLE
Unable to detect installed kernel on RPi4 (Centos 8)

### ISSUE THREAD

**Issue by MAngel666** [matteocorti/check_updates#46]
Message:
"CHECK_UPDATES UNKNOWN - Unable to detect installed kernel"

build and install on RPi4 CentOS 8

 - OS: CentOS
 - OS Version: CentOS Linux release 8.4.2105
 - check_updates Version: 1.8.4

check_updates -d -v:

[DBG] check_updates version: 1.8.4
[DBG] system info:           Linux valac.mgmt.chao5.net 5.10.74-v8.1.el8 #1 SMP PREEMPT Sat Oct 23 14:48:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
[DBG]                        NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
Checking a linux system
Running on CentOS Linux release 8.4.2105
[DBG] Updater: yum
Using Yum or DNF
running a Linux kernel: 5.10.74-v8.1
CHECK_UPDATES UNKNOWN - Unable to detect installed kernel

**Comment by matteocorti** [comment]
Do you have a custom kernel?

**Comment by matteocorti** [comment]
Are you running a custom kernel?

Can you please post the output of

```
rpm -qa | grep ^kernel'
```
?

**Comment by MAngel666** [comment]
rpm -qa | grep ^kernel
kernel-tools-libs-4.18.0-305.25.1.el8_4.aarch64
kernel-tools-4.18.0-305.25.1.el8_4.aarch64
kernel-headers-4.18.0-305.25.1.el8_4.aarch64

I dont use a custom kernel but the RPi kernels are not installed as rpm. It seems to be a specialty of the CentOS version fpr RPi4.

ll /boot/kernel*
-rwxr-xr-x. 1 root root 21619200 Jul 25 18:06 /boot/kernel-5.10.52-v8.1.el8.img
-rwxr-xr-x. 1 root root 21619200 Aug 21 18:45 /boot/kernel-5.10.60-v8.1.el8.img
-rwxr-xr-x. 1 root root 21619200 Oct 23 16:52 /boot/kernel-5.10.74-v8.1.el8.img
-rwxr-xr-x. 1 root root 21619200 Oct 24 16:44 /boot/kernel8.img

**Comment by matteocorti** [comment]
Ok then I propose to skip the kernel checks if the kernel is not installed as an RPM. The plugin would then only check the RPMs...

**Comment by matteocorti** [comment]
I just committed a new version but I don't have an RPi system to test. Can you please check?

**Comment by MAngel666** [comment]
/usr/lib64/nagios/plugins/check_updates -d -v
[DBG] check_updates version: 1.8.4
[DBG] running as:            root
[DBG] system info:           Linux valac.mgmt.chao5.net 5.10.74-v8.1.el8 #1 SMP PREEMPT Sat Oct 23 14:48:49 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
[DBG]                        NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
Checking a linux system
Running on CentOS Linux release 8.4.2105
[DBG] Updater: yum
Using Yum or DNF
running a Linux kernel: 5.10.74-v8.1
Unable to detect installed kernel: skipping kernel checks[DBG] Running "/bin/dnf check-update --assumeno --errorlevel=0 -q  2>&1"
CHECK_UPDATES OK - no updates available | total_updates=0;0;0 security_updates=0;0;0

btw: it would be nice if you add the new build dependency to spec file: perl-Module-Install

**Comment by matteocorti** [comment]
Seems to work. I'll add the missing newline in the verbose message and take a look at the dependency
