### ISSUE TITLE
Using both --security-only and --boot-check-warning

### ISSUE THREAD

**Issue by manikroy1** [matteocorti/check_updates#52]
**Describe the bug**

The server has both security update and new kernel. We have used both --security-only and --boot-check-warning in the command. Despite having security update, the plugin is reporting it as WARNING, not CRITICAL.

"CHECK_UPDATES WARNING - your machine is running kernel 3.10.0-1160.59.1 but a newer version (3.10.0-1160.71.1) is installed: you should reboot, 1 security update and 85 non-security updates available"

**To Reproduce**

* Find a server where both new kernel and security update are available
* Run check_updates with both --security-only and --boot-check-warning

**Expected behavior**

We were expecting CRITICAL alert as security updates is available but we are getting WARNING alert

**System (please complete the following information):**

 - OS: Linux centos
 - OS Version: 7
 - check_updates Version: 1.7.10

**Additional context/output**

$ /usr/lib64/nagios/plugins/check_updates -d --security-only -t 120 --clean --boot-check-warning 
[DBG] check_updates version: 1.7.10
[DBG] system info:           Linux *** 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[DBG]                        NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[DBG] Updater: yum
[DBG] Running "/usr/bin/yum clean all -q 2>&1"
[DBG] Running "/usr/bin/yum check-update --assumeno --errorlevel=0 -q  2>&1"
[DBG] 
...

[DBG] Running "/usr/bin/yum check-update --assumeno --errorlevel=0 -q  --security 2>&1 2>&1"
[DBG] 
[DBG] oniguruma.x86_64                        6.8.2-2.el7                         epel
CHECK_UPDATES WARNING - your machine is running kernel 3.10.0-1160.59.1 but a newer version (3.10.0-1160.71.1) is installed: you should reboot, 1 security update and 85 non-security updates available | total_updates=86;0;0 security_updates=1;0;0
oniguruma.x86_64 (security)

**Comment by matteocorti** [comment]
I just a committed a likely fix, but I have no current possibility to test. Can you please check if it works?

**Comment by manik-roy-m4** [comment]
Tested but the change doesn't work. I think you need to add the same source around line number 1176 which worked for me in my testing

https://github.com/matteocorti/check_updates/blob/master/check_updates#L1176

**Comment by manikroy1** [comment]
Tested but the change doesn't work. I think you need to add the same source around line number 1176 which worked for me in my testing

https://github.com/matteocorti/check_updates/blob/master/check_updates#L1176

**Comment by matteocorti** [comment]
Sorry missed it

**Comment by matteocorti** [comment]
Can you please test again?

**Comment by matteocorti** [comment]
Seems to work with my tests. I'll release a new version.
