### ISSUE TITLE
Description in the manual

### ISSUE THREAD

**Issue by manikroy1** [matteocorti/check_updates#53]
**Describe the bug**

Snippet from the 'check_updates' manual -
"
  --boot-check
    Check if the machine was booted with the newest kernel (default)
  --boot-check-warning
    Like --boot-check but state is warning instead of critical
 "

If a machine is booted newest kernel then that is the correct thing to do. Did you mean "... booted **without** the newest kernel (default)" ?

**To Reproduce**

Use the command below where there is a new kernel installed but the server has not been restarted yet

/usr/lib64/nagios/plugins/check_updates -d --security-only -t 300 --boot-check

**Expected behavior**

The program is producing correct result. Expecting a change on the manual.

**System (please complete the following information):**

 - OS: centos
 - OS Version: 7
 - check_updates Version: 1.7.10

**Additional context/output**

$ /usr/lib64/nagios/plugins/check_updates -d --security-only -t 300 --boot-check
[DBG] check_updates version: 1.7.10
[DBG] system info:           Linux test1 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[DBG]                        NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[DBG] Updater: yum
[DBG] Running "/usr/bin/yum check-update --assumeno --errorlevel=0 -q  2>&1"
[DBG] 
[DBG] acl.x86_64                           2.2.51-15.el7                 base         
[DBG] autofs.x86_64                        1:5.0.7-116.el7_9             local-updates
[DBG] avahi-libs.x86_64                    0.6.31-20.el7                 base         
[DBG] bash.x86_64                          4.2.46-35.el7_9               local-updates
...
[DBG] yum.noarch                           3.4.3-168.el7.centos          base         
[DBG] yum-plugin-fastestmirror.noarch      1.1.31-54.el7_8               base         
[DBG] yum-plugin-versionlock.noarch        1.1.31-54.el7_8               base         
[DBG] yum-utils.noarch                     1.1.31-54.el7_8               base         
[DBG] zlib.x86_64                          1.2.7-20.el7_9                local-updates
[DBG] Obsoleting Packages
[DBG] Running "/usr/bin/yum check-update --assumeno --errorlevel=0 -q  --security 2>&1 2>&1"
CHECK_UPDATES CRITICAL - your machine is running kernel 3.10.0-1160.66.1 but a newer version (3.10.0-1160.71.1) is installed: you should reboot, 217 non-security updates available | total_updates=217;0;0 security_updates=0;0;0

**Comment by manikroy1** [comment]
Sent a PR

**Comment by matteocorti** [comment]
Fixed with #54
