### ISSUE TITLE
EL8: readonly dependency

### ISSUE THREAD

**Issue by pille** [matteocorti/check_updates#55]
**Describe the bug**

on EL8 (e.g. AlmaLinux 8.6) `perl-Readonly` is also a **runtime requirement** (not only buildtime):

```
Can't locate Readonly.pm in @INC (you may need to install the Readonly module) (@INC contains: /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at /usr/lib64/nagios/plugins/check_updates line 29.
BEGIN failed--compilation aborted at /usr/lib64/nagios/plugins/check_updates line 29.
```

**To Reproduce**

freshly install AlmaLinux 8.6 and check_updates.

**Expected behavior**

plugin works

**System (please complete the following information):**

 - OS: EL8 (AlmaLinux 8)
 - OS Version: 8.6
 - check_updates Version: 2.0.0

**Comment by matteocorti** [comment]
Thanks, fixed the spec file and released an updated version
