### ISSUE TITLE
Use of uninitialized value $ENV{"HOME"} on Alma Linux 9

### ISSUE THREAD

**Issue by SMillerDev** [matteocorti/check_updates#57]
**Describe the bug**

Running the check through Icinga on Alma Linux 9, the output contains an issue:
```
Use of uninitialized value $ENV{"HOME"} in concatenation (.) or string at /usr/lib64/nagios/plugins/check_updates line 1108.
CHECK_UPDATES CRITICAL - 1 security update and 1 non-security update available 
c-ares.x86_64 (security)
telegraf.x86_64
```

**To Reproduce**

Have a user without a `$HOME` set and run the plugin

**Expected behavior**
Output without the error, such as:
```
CHECK_UPDATES CRITICAL - 1 security update and 1 non-security update available 
c-ares.x86_64 (security)
telegraf.x86_64
```

**System (please complete the following information):**

 - OS: Alma Linux
 - OS Version: 9.2
 - check_updates Version: 2.0.3 through EPEL

**Additional context/output**

If I run the command manually this problem does not occur. It seems Icinga suppresses `$HOME`, which I'm not sure is needed for this plugin anyway.

**Comment by matteocorti** [comment]
Thanks for the report. I just released version 2.0.4.
