### ISSUE TITLE
please add XCP-ng as distribution

### ISSUE THREAD

**Issue by vmpr** [matteocorti/check_updates#58]
thanks for your great work so far!

**Is your feature request related to a problem? Please describe.**

We would like to monitor outstanding yum packages on XCP-ng Servers, which are managed by yum, at the moment we get an error:

```
Use of uninitialized value $updater in concatenation (.) or string at /usr/lib64/nagios/plugins/check_updates line 1210.
Use of uninitialized value $updater in string eq at /usr/lib64/nagios/plugins/check_updates line 1212.
Use of uninitialized value $updater in string eq at /usr/lib64/nagios/plugins/check_updates line 1217.
CHECK_UPDATES UNKNOWN - unknown Linux distribution
```

XCP-ng is a virtualisation server based on centos7

**Describe the solution you'd like**

script should know that yum is the updater for XCP-ng

**Additional context**

here is the release file:
```
[05:49 XXX-int-xcp05 ~]# cat /etc/*release
XCP-ng release 8.2.1 (xenenterprise)
NAME="XCP-ng"
VERSION="8.2.1"
ID="xenenterprise"
ID_LIKE="centos rhel fedora"
VERSION_ID="8.2.1"
PRETTY_NAME="XCP-ng 8.2.1"
ANSI_COLOR="0;31"
HOME_URL="http://xcp-ng.org/"
BUG_REPORT_URL="https://github.com/xcp-ng/xcp"
XCP-ng release 8.2.1 (xenenterprise)
XCP-ng release 8.2.1 (xenenterprise)

**Comment by matteocorti** [comment]
Are you sure you are using this plugin?

I find no reference of a variable named ```$updater``` and I have no error message "unknown Linux distribution" in the code (I am printing "Cannot detect Linux distribution")

**Comment by vmpr** [comment]
Hi @matteocorti thank you for your reply, it is your script, but an older version:

```
#!/usr/bin/perl

eval 'exec /usr/bin/perl  -S $0 ${1+"$@"}'
    if 0; # not running under some shell

# nagios: -epn

package main;

# check_updates is a Nagios plugin to check if RedHat or Fedora system
# is up-to-date
#
# See  the INSTALL file for installation instructions
#
# Copyright (c) 2007-2020 Matteo Corti <matteo@corti.li>
#
# This module is free software; you can redistribute it and/or modify it
# under the terms of GNU general public license (gpl) version 3,
# or (at your option) any later version.
# See the COPYING file for details.

use 5.00800;

use strict;
use warnings;

no warnings 'once';    ## no critic (TestingAndDebugging::ProhibitNoWarnings)

our $VERSION = '1.7.10';
```

if installed it from epel 7:
`nagios-plugins-check-updates.x86_64                                                           1.7.10-2.el7                                                                     @epel`

`http://download.fedoraproject.org/pub/epel/7/`


can you still add the distribution and I will pull the script from github instead of epel?

cheers Ringo

**Comment by matteocorti** [comment]
I will gladly add it but I don't have a system to test.

Can you please post the output of ```uname -a``` and run the current version of the plugin?

**Comment by vmpr** [comment]
sure no worries:

```
[14:50 XXX-int-xcp05 ~]# uname -a
Linux XXX-int-xcp05 4.19.0+1 #1 SMP Thu Oct 12 13:19:25 CEST 2023 x86_64 x86_64 x86_64 GNU/Linux
```

ähm okay, I just deployed the actual version of the script on the server and it works:

```
[14:58 XXX-int-xcp05 ~]# perl /usr/lib64/nagios/plugins/check_updates
CHECK_UPDATES CRITICAL - your machine is running kernel 4.19.0+1 but a newer version (4.19.19-7.0.18.1.xcpng8.2) is installed: you should reboot, 4 non-security updates available | total_updates=4;0;0 security_updates=0;0;0
icinga2.x86_64
icinga2-bin.x86_64
icinga2-common.x86_64
microcode_ctl.x86_64
```

I did not expect that, sorry for wasting your time :( 

cheers Ringo

**Comment by matteocorti** [comment]
:-)

No problem. Glad that the plugin is useful!
