### ISSUE TITLE
Kernel warning overrides security alerts

### ISSUE THREAD

**Issue by tilghman** [matteocorti/check_updates#60]
On some of our servers, we have to schedule reboots to handle a kernel update, to avoid outages.  For example, our core database server has to be rebooted on the weekend.  When additional security upgrades are released in the interim, the check_updates plugin continues to flag the service as a WARNING state, instead of CRITICAL

When security packages are available, the tool should indicate CRITICAL, and an unapplied kernel update should not affix the status to WARNING.

 - OS: RHEL
 - OS Version: 8.10
 - check_updates Version: 1.8.4

[DBG] check_updates version: 1.8.4
[DBG] running as:            root
[DBG] system info:           Linux rheldb84 4.18.0-553.8.1.el8_10.x86_64 #1 SMP Fri Jun 14 03:19:37 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
[DBG]                        NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
Checking a linux system
Running on Red Hat Enterprise Linux release 8.10 (Ootpa)
[DBG] Updater: yum
Using Yum or DNF
running a Linux kernel: 4.18.0-553.8.1
kernel: running = 4.18.0-553.8.1, installed = 4.18.0-553.16.1
[DBG] Running "/bin/dnf check-update --nogpgcheck --assumeno --errorlevel=0 -q  2>&1"
[DBG] 
[DBG] httpd.x86_64                2.4.37-65.module+el8.10.0+22196+d82931da.2 rhel-8-for-x86_64-appstream-rpms
[DBG] httpd-filesystem.noarch     2.4.37-65.module+el8.10.0+22196+d82931da.2 rhel-8-for-x86_64-appstream-rpms
[DBG] httpd-tools.x86_64          2.4.37-65.module+el8.10.0+22196+d82931da.2 rhel-8-for-x86_64-appstream-rpms
[DBG] postgresql14.x86_64         14.13-2PGDG.rhel8                          pgdg14                          
[DBG] postgresql14-contrib.x86_64 14.13-2PGDG.rhel8                          pgdg14                          
[DBG] postgresql14-libs.x86_64    14.13-2PGDG.rhel8                          pgdg14                          
[DBG] postgresql14-server.x86_64  14.13-2PGDG.rhel8                          pgdg14                          
[DBG] Security: kernel-core-4.18.0-553.16.1.el8_10.x86_64 is an installed security update
[DBG] Security: kernel-core-4.18.0-553.8.1.el8_10.x86_64 is the currently running version
Security updates available
[DBG] Running "/bin/dnf check-update --nogpgcheck --assumeno --errorlevel=0 -q  --security 2>&1 2>&1"
UPDATES UNKNOWN - plugin timed out (timeout 15s)

**Comment by matteocorti** [comment]
Can you please upgrade to the current version?

As far as I can check, this should no more be a problem:

```
if ( @outdated >= $options->get('warning') ) {
    if ( $status != Monitoring::Plugin->CRITICAL ) {

        # if we have a critical status for something else the status stays critical
        $status = Monitoring::Plugin->WARNING;
    }
}
```

**Comment by tilghman** [comment]
Upgraded to the current Github code.  It still works, although I'll have to wait for the next security update to confirm the fix, as the previous issue was already applied.

**Comment by tilghman** [comment]
Well, that was fast (21 security updates just now).  Yes, works exactly as desired.
